provider:
  name: uberspace
resources:
  maildomain:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{name}/
      method: GET
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{name}/
      method: DELETE
  mailuser:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{maildomain_name}/users/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{maildomain_name}/users/{local}/
      method: GET
    update:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{maildomain_name}/users/{local}/
      method: PATCH
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/maildomains/{maildomain_name}/users/{local}/
      method: DELETE
  sshkey:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/sshkeys/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/sshkeys/{id}/
      method: GET
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/sshkeys/{id}/
      method: DELETE
  webdomain:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{name}/
      method: GET
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{name}/
      method: DELETE
  webdomain_backend:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/backends/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/backends/{path}/
      method: GET
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/backends/{path}/
      method: DELETE
  webdomain_header:
    create:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/headers/
      method: POST
    read:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/headers/{id}/
      method: GET
    delete:
      path: /api/v1/external/asteroids/{asteroid_name}/webdomains/{webdomain_name}/headers/{id}/
      method: DELETE
